import argparse

parser = argparse.ArgumentParser()

parser.add_argument('--vocab_size', type=int, default=5000)
parser.add_argument('--num_sampled', type=int, default=1000)
parser.add_argument('--max_len', type=int, default=30)
parser.add_argument('--word_dropout_rate', type=float, default=0.2)
parser.add_argument('--batch_size', type=int, default=128)
parser.add_argument('--embedding_dim', type=int, default=128)
parser.add_argument('--encoder_net', type=str, default='rnn')
parser.add_argument('--cnn_filters', type=int, default=250)
parser.add_argument('--cnn_kernel_size', type=int, default=3)
parser.add_argument('--rnn_cell', type=str, default='gru')
parser.add_argument('--rnn_size', type=int, default=128)
parser.add_argument('--encoder_layers', type=int, default=2)
parser.add_argument('--decoder_layers', type=int, default=2)
parser.add_argument('--beam_width', type=int, default=5)
parser.add_argument('--clip_norm', type=float, default=5.0)
parser.add_argument('--latent_size', type=int, default=16)
parser.add_argument('--anneal_max', type=float, default=1.0)
parser.add_argument('--anneal_bias', type=int, default=6000)
parser.add_argument('--mutinfo_sleep_steps', type=int, default=3000)
parser.add_argument('--no_kl_anneal', action='store_true')
parser.add_argument('--num_epoch', type=int, default=20)
parser.add_argument('--display_loss_step', type=int, default=50)
parser.add_argument('--display_text_step', type=int, default=300)

parser.set_defaults(no_kl_anneal=False)

args = parser.parse_args()
