import argparse

parser = argparse.ArgumentParser()

parser.add_argument('--vocab_size', type=int, default=20000)
parser.add_argument('--num_sampled', type=int, default=1000)
parser.add_argument('--num_class', type=int, default=2)
parser.add_argument('--max_len', type=int, default=15)
parser.add_argument('--word_dropout_rate', type=float, default=0.8)
parser.add_argument('--batch_size', type=int, default=128)
parser.add_argument('--embedding_dim', type=int, default=128)
parser.add_argument('--rnn_size', type=int, default=512)
parser.add_argument('--cnn_filters', type=int, default=128)
parser.add_argument('--cnn_dropout_rate', type=float, default=0.5)
parser.add_argument('--beam_width', type=int, default=5)
parser.add_argument('--clip_norm', type=float, default=5.0)
parser.add_argument('--latent_size', type=int, default=16)
parser.add_argument('--kl_anneal_max', type=float, default=1.0)
parser.add_argument('--kl_anneal_bias', type=int, default=6000)
parser.add_argument('--temperature_anneal_max', type=float, default=1.0)
parser.add_argument('--temperature_anneal_bias', type=int, default=6000)
parser.add_argument('--temperature_start_step', type=int, default=19000)
parser.add_argument('--lambda_c', type=float, default=0.1)
parser.add_argument('--lambda_z', type=float, default=0.1)
parser.add_argument('--lambda_u', type=float, default=0.1)
parser.add_argument('--beta', type=float, default=0.1)
parser.add_argument('--stage_1_num_epochs', type=int, default=25)
parser.add_argument('--stage_2_num_epochs', type=int, default=25)
parser.add_argument('--stage_1_display_step', type=int, default=50)
parser.add_argument('--stage_2_display_step', type=int, default=10)

args = parser.parse_args()
